const Status = {
  CREATED: 201, // CREATION SUCCESSFULL E.G USER REGISTER SUCCESS
  OK: 200, // SUCCESS FETCH
  BAD_REQUEST: 400, // WRONG INPUTS
  CONFLICT: 409, // USER / CATEGORY ALREADY EXIST
  NOT_FOUND: 404, // USER NOT FOUND
  UNAUTHORISED: 401,
};

export default Status;
